package db

import (
	"context"
	"database/sql"
	"fmt"
)

// The Store provides all functions to execute db queries and transactions.
// For queries, we already have basic queries generated by `sqlc`, see `Queries` from `db.go`.
// This however does not support transactions, thereof we extend this functionality here.
// This is called a "composition" and is the preferred way to extend functionality in Go
type Store struct {
	*Queries
	db *sql.DB
}

// Creates new store
func NewStore(db *sql.DB) *Store {
	return &Store{
		db:      db,
		Queries: New(db),
	}
}

// Executes a function within database transaction
func (store *Store) execTx(ctx context.Context, fn func(*Queries) error) error {
	// In the case of Postgres, the default isolation level is Read-committed.
	// If we wanted to change it, we would pass in `&sql.TxOptions{...}` instead of nil
	tx, err := store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	q := New(tx)
	err = fn(q)
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %w, rb err: %w", err, rbErr)
		}
		return err
	}

	return tx.Commit()
}

// Contains the input parameters to transfer money between accounts
type TransferTxParams struct {
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	Amount        int64 `json:"amount"`
}

// Contains the result of a transfer transaction
type TransferTxResult struct {
	Transfer    Transfer `json:"transfer"`
	FromAccount Account  `json:"from_account"`
	ToAccount   Account  `json:"to_account"`
	FromEntry   Entry    `json:"from_entry"`
	ToEntry     Entry    `json:"to_entry"`
}

// Performs a money transfer from one account to the other.
// It creates a transfer record, adds account entries, and updates accounts' balance within a single transaction
func (store *Store) TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error) {
	var result TransferTxResult

	err := store.execTx(ctx, func(q *Queries) error {
		var err error

		// Check error: should convert arg (type TransferTxParams) to CreateTransferParams instead of using struct literal (S1016)go-staticcheck
		// result.Transfer, err = q.CreateTransfer(ctx, CreateTransferParams{
		// 	FromAccountID: arg.FromAccountID,
		// 	ToAccountID:   arg.ToAccountID,
		// 	Amount:        arg.Amount,
		// })

		// Convert from one structure to another when the properties match:
		result.Transfer, err = q.CreateTransfer(ctx, CreateTransferParams(arg))
		if err != nil {
			return err
		}

		result.FromEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.FromAccountID,
			Amount:    -arg.Amount,
		})
		if err != nil {
			return err
		}

		result.ToEntry, err = q.CreateEntry(ctx, CreateEntryParams{
			AccountID: arg.ToAccountID,
			Amount:    arg.Amount,
		})
		if err != nil {
			return err
		}

		// TODO: Update accounts' balance

		return nil
	})

	return result, err
}
